# Generated by Django 5.2.6 on 2025-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_distance', models.FloatField(db_index=True)),
                ('category', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'taxi_trip',
            },
        ),
    ]
