# Generated by Django 5.2.6 on 2025-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=3)),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.PositiveIntegerField()),
                ('trip_distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('rate_code', models.PositiveSmallIntegerField()),
                ('store_and_fwd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('payment_type', models.CharField(max_length=3)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('surcharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mta_tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tip_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tolls_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'taxi_trips',
                'indexes': [models.Index(fields=['trip_distance'], name='taxi_trips_trip_di_b68461_idx')],
            },
        ),
    ]
