# Generated by Django 5.2.6 on 2025-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=3)),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.PositiveIntegerField()),
                ('trip_distance', models.FloatField(db_index=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('rate_code', models.PositiveSmallIntegerField()),
                ('store_and_fwd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('payment_type', models.CharField(max_length=3)),
                ('fare_amount', models.FloatField()),
                ('surcharge', models.FloatField()),
                ('mta_tax', models.FloatField()),
                ('tip_amount', models.FloatField()),
                ('tolls_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('category', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'taxi_trip',
                'indexes': [models.Index(fields=['trip_distance'], name='taxi_trip_trip_di_043a51_idx')],
            },
        ),
    ]
