# Generated by Django 5.2.6 on 2025-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taxitrip',
            index=models.Index(fields=['category'], name='taxi_trip_categor_93eed2_idx'),
        ),
    ]
