# Generated by Django 5.2.6 on 2025-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='fare_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='mta_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='surcharge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='tip_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='tolls_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='trip_distance',
            field=models.FloatField(db_index=True),
        ),
    ]
