# Generated by Django 5.2.6 on 2025-09-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taxitrip',
            index=models.Index(fields=['trip_distance'], name='taxi_trip_trip_di_043a51_idx'),
        ),
        migrations.AddIndex(
            model_name='taxitrip',
            index=models.Index(fields=['category'], name='taxi_trip_categor_93eed2_idx'),
        ),
    ]
